### ISSUE TITLE
API Link displaying while no access to location

### ISSUE THREAD

**Issue by vikramnr** [AndreyAzimov/whentosurf#3]
![image](https://cloud.githubusercontent.com/assets/8538409/23090627/2cfb4b68-f5c8-11e6-964c-198ddbc59f2d.png)

Hi,

I read about your app on medium and while trying out I found this one.

Kindly close it if it's not much of an issue.

**Comment by AndreyAzimov** [comment]
Hi man,

Thanks for feedback

Fixed.

--
Cheers,

Andrey.

Stay touch in *Twitter* <https://twitter.com/AndreyAzimov>

**Comment by vikramnr** [comment]
Great :+1:
